/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConnectionsTransactionsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5568762278705133190L;
    private String connectionUuid;
    private String createdAt;
    private String createdBy;
    private String jobId;
    private String name;
    private LinkedHashMap<String, Object> status;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("connection_uuid")
    public String getConnectionUuid ( ) { 
        return this.connectionUuid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("connection_uuid")
    public void setConnectionUuid (String value) { 
        this.connectionUuid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("created_at")
    public String getCreatedAt ( ) { 
        return this.createdAt;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("created_at")
    public void setCreatedAt (String value) { 
        this.createdAt = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("created_by")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("created_by")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("job_id")
    public String getJobId ( ) { 
        return this.jobId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("job_id")
    public void setJobId (String value) { 
        this.jobId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public LinkedHashMap<String, Object> getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (LinkedHashMap<String, Object> value) { 
        this.status = value;
    }
 
}
 