/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;

public class ConnectionsBuyersResponseBuilder {
    //the instance to build
    private ConnectionsBuyersResponse connectionsBuyersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ConnectionsBuyersResponseBuilder() {
        connectionsBuyersResponse = new ConnectionsBuyersResponse();
    }

    public ConnectionsBuyersResponseBuilder connectionUuid(String connectionUuid) {
        connectionsBuyersResponse.setConnectionUuid(connectionUuid);
        return this;
    }

    public ConnectionsBuyersResponseBuilder createdAt(String createdAt) {
        connectionsBuyersResponse.setCreatedAt(createdAt);
        return this;
    }

    public ConnectionsBuyersResponseBuilder createdBy(String createdBy) {
        connectionsBuyersResponse.setCreatedBy(createdBy);
        return this;
    }

    public ConnectionsBuyersResponseBuilder jobId(String jobId) {
        connectionsBuyersResponse.setJobId(jobId);
        return this;
    }

    public ConnectionsBuyersResponseBuilder name(String name) {
        connectionsBuyersResponse.setName(name);
        return this;
    }

    public ConnectionsBuyersResponseBuilder status(LinkedHashMap<String, Object> status) {
        connectionsBuyersResponse.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConnectionsBuyersResponse build() {
        return connectionsBuyersResponse;
    }
}