/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;

public class ConnectionsTransactionsResponseBuilder {
    //the instance to build
    private ConnectionsTransactionsResponse connectionsTransactionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ConnectionsTransactionsResponseBuilder() {
        connectionsTransactionsResponse = new ConnectionsTransactionsResponse();
    }

    public ConnectionsTransactionsResponseBuilder connectionUuid(String connectionUuid) {
        connectionsTransactionsResponse.setConnectionUuid(connectionUuid);
        return this;
    }

    public ConnectionsTransactionsResponseBuilder createdAt(String createdAt) {
        connectionsTransactionsResponse.setCreatedAt(createdAt);
        return this;
    }

    public ConnectionsTransactionsResponseBuilder createdBy(String createdBy) {
        connectionsTransactionsResponse.setCreatedBy(createdBy);
        return this;
    }

    public ConnectionsTransactionsResponseBuilder jobId(String jobId) {
        connectionsTransactionsResponse.setJobId(jobId);
        return this;
    }

    public ConnectionsTransactionsResponseBuilder name(String name) {
        connectionsTransactionsResponse.setName(name);
        return this;
    }

    public ConnectionsTransactionsResponseBuilder status(LinkedHashMap<String, Object> status) {
        connectionsTransactionsResponse.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConnectionsTransactionsResponse build() {
        return connectionsTransactionsResponse;
    }
}