/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class HttpApiItembaseIoV1JobV10SchemaJson 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5642667349546973642L;
    private String connectionUuid;
    private String createdAt;
    private String createdBy;
    private String finishedAt;
    private String jobId;
    private String name;
    private LinkedHashMap<String, Object> request;
    private LinkedHashMap<String, Object> result;
    private Status status;
    /** GETTER
     * Connection uuid for which this job was created.
     */
    @JsonGetter("connection_uuid")
    public String getConnectionUuid ( ) { 
        return this.connectionUuid;
    }
    
    /** SETTER
     * Connection uuid for which this job was created.
     */
    @JsonSetter("connection_uuid")
    public void setConnectionUuid (String value) { 
        this.connectionUuid = value;
    }
 
    /** GETTER
     * An ISO 8601 date format, i.E. YYYY-MM-DDThh:mm:ss.sTZD.
     */
    @JsonGetter("created_at")
    public String getCreatedAt ( ) { 
        return this.createdAt;
    }
    
    /** SETTER
     * An ISO 8601 date format, i.E. YYYY-MM-DDThh:mm:ss.sTZD.
     */
    @JsonSetter("created_at")
    public void setCreatedAt (String value) { 
        this.createdAt = value;
    }
 
    /** GETTER
     * Contains the origin of the job.
     */
    @JsonGetter("created_by")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * Contains the origin of the job.
     */
    @JsonSetter("created_by")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
    }
 
    /** GETTER
     * An ISO 8601 date format, i.E. YYYY-MM-DDThh:mm:ss.sTZD.
     */
    @JsonGetter("finished_at")
    public String getFinishedAt ( ) { 
        return this.finishedAt;
    }
    
    /** SETTER
     * An ISO 8601 date format, i.E. YYYY-MM-DDThh:mm:ss.sTZD.
     */
    @JsonSetter("finished_at")
    public void setFinishedAt (String value) { 
        this.finishedAt = value;
    }
 
    /** GETTER
     * Unique identifier of the job
     */
    @JsonGetter("job_id")
    public String getJobId ( ) { 
        return this.jobId;
    }
    
    /** SETTER
     * Unique identifier of the job
     */
    @JsonSetter("job_id")
    public void setJobId (String value) { 
        this.jobId = value;
    }
 
    /** GETTER
     * Job name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Job name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Contains all request parameters needed to execute the job.
     */
    @JsonGetter("request")
    public LinkedHashMap<String, Object> getRequest ( ) { 
        return this.request;
    }
    
    /** SETTER
     * Contains all request parameters needed to execute the job.
     */
    @JsonSetter("request")
    public void setRequest (LinkedHashMap<String, Object> value) { 
        this.request = value;
    }
 
    /** GETTER
     * Contains all results of job execution.
     */
    @JsonGetter("result")
    public LinkedHashMap<String, Object> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * Contains all results of job execution.
     */
    @JsonSetter("result")
    public void setResult (LinkedHashMap<String, Object> value) { 
        this.result = value;
    }
 
    /** GETTER
     * Job status.
     */
    @JsonGetter("status")
    public Status getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Job status.
     */
    @JsonSetter("status")
    public void setStatus (Status value) { 
        this.status = value;
    }
 
}
 