/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Status 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5549941498322778458L;
    private String description;
    private NameEnum name;
    /** GETTER
     * Status description.
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * Status description.
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * Status name.
     */
    @JsonGetter("name")
    public NameEnum getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Status name.
     */
    @JsonSetter("name")
    public void setName (NameEnum value) { 
        this.name = value;
    }
 
}
 