/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.models;

import java.util.*;

public class StatusBuilder {
    //the instance to build
    private Status status;

    /**
     * Default constructor to initialize the instance
     */
    public StatusBuilder() {
        status = new Status();
    }

    /**
     * Status description.
     */
    public StatusBuilder description(String description) {
        status.setDescription(description);
        return this;
    }

    /**
     * Status name.
     */
    public StatusBuilder name(NameEnum name) {
        status.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Status build() {
        return status;
    }
}