/*
 * ConnectorAPI
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2016
 */
package io.itembase.connector.interfaces;

import java.util.*;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import io.itembase.connector.models.*;

public interface JobsInterface {
    /**
     * Get job details
     * @param    jobId    Required parameter: Job id
	 * @return	Returns the LinkedHashMap<String, Object> response from the API call*/
    @GET
    @Path("/jobs/{jobId}")
    @Produces(MediaType.WILDCARD)
    public LinkedHashMap<String, Object> getJobsByJobId(
            @PathParam("jobId") String jobId);
}